### ISSUE TITLE
It is necessary to add a comma in the device ID in the AUTOCONFIG table

### ISSUE THREAD

**Issue by robertpolli** [lnls-sirius/bbb-function#50]
When the device ID is unique, it is necessary add a comma before the number, as shown below, for the AutoConfig.py script find the device correctly. 

![image](https://github.com/lnls-sirius/bbb-function/assets/51081790/0fe44555-ead1-4d73-b924-3bc6568b4978)

**Comment by pnallin** [comment]
@robertpolli I suppose it was fixed on PR #49 .
Can we close this issue ?
